apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: joomla
  name: joomla
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: joomla
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: joomla
    spec:
      containers:
        - env:
            - name: JOOMLA_DB_HOST
              value: joomladb
            - name: JOOMLA_DB_PASSWORD
              value: example
          image: joomla
          name: joomla
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
