apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: joomladb
  name: joomladb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: joomladb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: joomladb
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
          image: mysql:5.6
          name: joomladb
          resources: {}
      restartPolicy: Always
status: {}
